### ISSUE TITLE
Sparse Structure Selection (ECCV 2018)

### ISSUE THREAD

**Issue by rogercmq** [youzhonghui/gate-decorator-pruning#12]
(｡･∀･)ﾉﾞ嗨，感谢您的工作，是非常简单有效的方法！

ECCV2018有一篇图森科技的工作，也是用一个可训练的标量去衡量通道重要性，文章在此[Data-Driven Sparse Structure Selection for Deep Neural Networks](http://winsty.net/papers/sss.pdf)，不知道您有没有与此文章做过比较。

**Comment by youzhonghui** [comment]
因为投稿篇幅限制， 我们没有在文章中加入和这篇论文的比较。 但是实验结果是可以直接比较的，因为这篇文章和我们都做了 ResNet50 在 ImageNet 上的减枝实验.  在 Data-Driven Sparse Structure Selection for Deep Neural Networks 论文中的Table 2可以看到， 在减少 43% 计算量的情况下， 网络的 Top-1 acc是 71.82%， 我们报告的实验结果是 减少 55%计算量的情况下， 保持 75.18% 的Top-1 acc
