### ISSUE TITLE
AttributeError: 'Resnet50' object has no attribute 'classifier'

### ISSUE THREAD

**Issue by simon5u** [youzhonghui/gate-decorator-pruning#14]
Hi, I tried to modify your code by using the imagenet's resnet50 on cifar10. I followed the vgg16 example and changed it to resnet50. However, I got the following error when running the pruning, CUDA_VISIBLE_DEVICES=0 python ./run/resnet-50/resnet50_prune_demo.py --config ./run/resnet-50/prune.json.

  File "/home/ccng/anaconda3/envs/gatedeco/lib/python3.7/site-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'Resnet50' object has no attribute 'classifier'

May I know how to resolve this error? Thanks.

**Comment by simon5u** [comment]
Hi, I resolved it by changing the following line in resnet50_prune_demo.py:-

    cloned.module.classifier = FinalLinearObserver(cloned.module.classifier)

to 

    cloned.module.classifier = FinalLinearObserver(cloned.module.backbone.fc)

However, I got another error, 

  **File "/home/ccng/anaconda3/envs/gatedeco/lib/python3.7/site-packages/torchvision/models/resnet.py", line 112, in forward
    out += identity
RuntimeError: The size of tensor a (256) must match the size of tensor b (255) at non-singleton dimension 1**

Please help, thanks.

**Comment by moliq1** [comment]
Hi, I also tried the resnet50 model, what I do is changing the
 `cloned.module.classifier = FinalLinearObserver(cloned.module.classifier)`
to
`    cloned.module.backbone.fc = FinalLinearObserver(cloned.module.backbone.fc)`

but I also got an error, 
`File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)`
`File "/usr/local/lib/python3.5/dist-packages/torchvision/models/resnet.py", line 108, in forward
    out += identity`
`RuntimeError: The size of tensor a (248) must match the size of tensor b (242) at non-singleton dimension 1`

It seems like at the first bottleneck, after performing the pruning, the feature map size is no longer equal between the shortcut. I'm wondering what's the difference between the resnet56 you implemented and the resnet50,  how to fix the problem?

**Comment by youzhonghui** [comment]
Sorry for the late reply. The CIFAR images is too small for resnet-50 which is originally designed to classify ImageNet (224x224). The error comes from the network downsampling. A simple way to solve this problem is to upsample the input images to 64x64. However, it is still not recommended to apply resnet-50 to the CIFAR datatsets (instead, resnet-56 is designed for CIFAR).
