### ISSUE TITLE
TypeError: Object of type 'Config' is not JSON serializable

### ISSUE THREAD

**Issue by niam06** [youzhonghui/gate-decorator-pruning#15]
Hi, 

Thank you for your excellent work.

When running your "Command line (VGG-16) demo", I get a JSON encoder error in logger.py at line 63 under the save_network function - "TypeError: Object of type 'Config' is not JSON serializable". Can you please suggest a fix to this issue? 

PS- I am using python 3.6.10 and PyTorch 1.0.1.post2. 

Best,
Niam

**Comment by youzhonghui** [comment]
Oh it's a bug caused by last code update. But don't worry, just run the command again to solve the problem. I will fix the code later.

**Comment by niam06** [comment]
Thanks! Please give a shout here once you fix it :)

**Comment by Ling27** [comment]
Hey, I experienced the same issue when saving the model (after 80 epochs) with command: 

CUDA_VISIBLE_DEVICES=0 python main.py --config ./run/vgg16/baseline.json

Could you please fix the code? thank you in advance

**Comment by youzhonghui** [comment]
Already fixed. enjoy :D

**Comment by priscillapan** [comment]
still not correct。 logger.py  L68  should be "json.dump(cfg.raw(), fp)" @youzhonghui

**Comment by youzhonghui** [comment]
Yes, you are right. Thank you very much!
