### ISSUE TITLE
How to save pruned model?

### ISSUE THREAD

**Issue by cvJie** [youzhonghui/gate-decorator-pruning#5]
I run the examples ,
    for point in [i for i in list(flops_save_points)]:
        if flops_ratio <= point:
             torch.save(pack.net.module.state_dict(), './logs/fashion_ticktock/%s.pth' % str(point)),

But ,seved model size never change to small.

**Comment by youzhonghui** [comment]
After the Tick-Tock phase, the gate is set to zero, but the filter is still preserved. To get the pruned network, you need to "melt" those useless filters. You can save the pruned model after "melt".

https://github.com/youzhonghui/gate-decorator-pruning/blob/4f8759645741bcc08479068ed8ea4db315d405ff/run/vgg16/vgg16_prune_demo.py#L115-L118
