### ISSUE TITLE
MACs vs. Flops

### ISSUE THREAD

**Issue by GreenRandomDinosaur** [youzhonghui/gate-decorator-pruning#7]
Hello, I have a question about the way you counted FLOPs.
According to your code prune/utils.py, you used thop. 
However, the code is recently corrected that it actually measured MACs rather than FLOPs. 
(Please refer to https://github.com/Lyken17/pytorch-OpCounter/issues/37
and https://github.com/Lyken17/pytorch-OpCounter/commit/41fd65c9035bd06638b85fbdb05da41f76afe477)

In this case, are the FLOPs values in your paper still valid? 

Thank you.
Jung

**Comment by youzhonghui** [comment]
Thank you very much. I am traveling these days. I will look into it in detail later.

**Comment by youzhonghui** [comment]
According to the following description of MACs and FLOPs differences,  roughly MACs = 2 * FLOPs, which would not affect the FLOPs pruning ratio that reported in our paper.
https://github.com/sovrasov/flops-counter.pytorch/issues/16#issuecomment-518585837
